import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { login } from '../lensapi/auth/login-user';
import { useState } from 'react';
import Image from 'next/image';
import hero from '../public/images/hero.jpg';
import { createProfile } from '../lensapi/profile/profile';
import toast, { Toaster } from 'react-hot-toast';
import { useRouter } from 'next/router'
import { Renderable, ValueFunction, Toast } from 'react-hot-toast/dist/core/types';

const Home: NextPage = () => {
    const [active, setActive] = useState(true);
    const router = useRouter();
    const toastSuccess = (message: Renderable | ValueFunction<Renderable, Toast>) => toast.success(message, {
      ariaProps: {
        role: 'status',
        'aria-live': 'polite',
      },
    });

    const toastFail = (message: Renderable | ValueFunction<Renderable, Toast>) => toast.success(message, {
      ariaProps: {
        role: 'status',
        'aria-live': 'polite',
      },
    });

  
  const handleConnect = async () => {
      setActive(false);
      let answer = await login()
        .then(()=> {
          toastSuccess('Successfully logged in!')
          router.push('/signup');
        })
        .catch(()=> {
          toastFail('Something went wrong. Refresh!');
        })
        setActive(true);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.home}>
        <section className={styles.left}>
          <Image src={hero} alt="hero" layout="fill" objectFit="cover"/>
        </section>
        <section className={styles.right}>
          <h1 className={styles.h1}>Get Uncaged</h1>
          <h2 className={styles.h2}>A social network that doesn&apos;t box you in. It&apos;s your life!</h2>
          <button className={active? styles.button : styles.inactivebutton} disabled={!active} onClick={handleConnect}>connect wallet</button>
          <Toaster 
            containerClassName={styles.toaster}
            toastOptions={{
              duration: 50000000,
              success: {
                duration: 3000,
                theme: {
                  primary: 'green',
                  secondary: 'black',
                },
              },
            }}
          />
        </section>
        </div>
      </main>
    </div>
  )
}

export default Home
