import Head from 'next/head'
import { getAllProfiles } from '../lensapi/profile/profile';
import { useState } from 'react';
import Header from '../components/Header';
import styles from '../styles/Profile.module.css'

const Profile = () => {
    const [profiles, setProfiles] = useState([]);
    const getProfile = async () => {
        const profile = await getAllProfiles();
        setProfiles(profile.data.profiles.items);
    }

    getProfile();

    return (
    <div className={styles.container}>
        <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
          <div className={styles.leftSide}>
              <p>Hey</p>
          </div>
          <div className={styles.rightSide}>
              <div className={styles.nav}>
                <div className={styles.banners}>global profile</div>
                <div className={styles.banners}>Your stuff</div>
                <div className={styles.banners}>Discover Communities</div>
              </div>
            <div>
                <div className={styles.statuses}>
                    <p>Hey there comrades.</p>
                </div>
            </div>
            <div>
            </div>
          </div>
      </main>
    </div>
    )
}

export default Profile;