import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { login } from '../lensapi/auth/login-user';
import { useState } from 'react';
import Image from 'next/image';
import hero from '../public/images/hero.jpg';
import { createProfile } from '../lensapi/profile/profile';

const Home: NextPage = () => {
    const [response, setResponse] = useState('');

  const doStuff = async () => {
      let answer = await login()
      answer.data?.authenticate?.accessToken
        ? setResponse('Successfully logged in!')
        : setResponse('Something went wrong. Refresh!')
  }
  const createProfileAcc = async () => {
    await createProfile("mogwai");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.home}>
        <section className={styles.left}>
          <Image src={hero} alt="hero" layout="fill" objectFit="cover"/>
        </section>
        <section className={styles.right}>
          <h1 className={styles.h1}>Get Uncaged</h1>
          <h2 className={styles.h2}>A social network that doesn&apos;t box you in. It&apos;s your life!</h2>
          <button className={styles.button} onClick={doStuff}>connect wallet</button>
        </section>
        </div>
      </main>
    </div>
  )
}

export default Home
